### ISSUE TITLE
sorry to contact you this way

### ISSUE THREAD

**Issue by rickyi22** [fujiaoliu/rezina#2]
i happen to see your reply about k-means algorithem, i am a new ML python learner and i was wonder if my data are a bunch of more than 3 dimension number, such as [[1,1,2,3],[2,2,1,2],[1,1,2,3]], how could i get the cluster of this dataset by using k-means python :)

**Comment by fujiaoliu** [comment]
Hi @rickyi22, you could use sklearn to get your clusters. for example,

```
>>>from sklearn.cluster import KMeans
>>>import numpy as np
>>>X = np.array([[1,1,2,3],[2,2,1,2],[1,1,2,3]])
>>>kmeans = KMeans(n_clusters=2, random_state=0).fit(X)  # divided data into two clusters
>>>kmeans.labels_
array([0, 1, 0], dtype=int32)
>>>kmeans.cluster_centers_
array([[ 1.,  1.,  2.,  3.], [ 2.,  2.,  1.,  2.]])
>>>kmeans.predict([[0, 0, 0, 0], [3, 1, 3, 4]])
array([1, 0], dtype=int32)

```

**Comment by rickyi22** [comment]
Big thanks, Sorry for taking so long to reply, i forgot to check this issue recently , i'd like to give it a try as you recommended :)  really appreciated 
if there are any other follow-up questions, can i still contact you here or some other way :)  i'm Chinese too~

**Comment by fujiaoliu** [comment]
@rickyi22 , 当然可以，不过我可能不能及时回复你， 不过我看到了一定会回复你的。

**Comment by rickyi22** [comment]
@fujiaoliu 这个KMeans里面的参数precompute_distances  和 tols、verbose 不是很懂是什么意思额   有参数可以设置 相隔多少距离以上才算一个cluster么 :)

**Comment by fujiaoliu** [comment]
@rickyi22 ， 参数的具体意思你可以看看manual.  kmeans 不支持你说的“相隔多少距离以上才算一个cluster么 ” 这个功能， 如果你想把一个cluster进一步分成多个， 你可以调大K的值。
